Feat templates
R2D2-2017/R2D2-2017 pull request #1
Opened 2017-05-18 17:37 UTC by sqrtroot

Created templates to start developing for the following targets:

- pc
- pi
- arduino due

building for arduino due on windows pc's requires mingw make

2017-05-18 17:50 UTC, ManDeJan submitted a review, later dismissed
Approved, all targets where easy to build, and get running. We should add a wiki page for how to use BMPTK++

2017-05-18 18:00 UTC, LuukSteeman commented
@cjsmeele als ik een module aanmaak met pc als target krijg ik geen visual studio solution

2017-05-18 18:02 UTC, LuukSteeman commented
nope nvm, verkeerd gekeken

2017-05-18 18:04 UTC, LuukSteeman requested changes
Add documentation, everything else looks fine

2017-05-18 18:08 UTC, cjsmeele commented
@LuukSteeman Thanks for the feedback!

@sqrtroot @ManDeJan, Feature idea: We should probably add a parameter / prompt to allow people to override the cmake generator, so that people can use bmptk++ to generate files for IDEs other than the default for their host platform.

2017-05-18 18:12 UTC, LuukSteeman commented
Maybe make it so that double clicking on bmptk++.py works as well. Right now it just opens and closes a cmd window if you do that.
Would be a bit more intuitive than using cmd to run the script.

2017-05-18 20:03 UTC, LuukSteeman commented
console works on windows

2017-05-18 21:56 UTC, cjsmeele commented
Re Documentation: I'm currently writing [Development Workflow](https://github.com/R2D2-2017/R2D2-2017/wiki/Development-Workflow) on the wiki, which includes instructions on running bmptk++.

2017-05-18 22:35 UTC, LuukSteeman commented
allright, notify me when it's done so i can take a look. if that's all good this can be merged

2017-05-19 07:26 UTC, sqrtroot reviewed
Maybe we have to have a look at these points?

2017-05-19 07:26 UTC, sqrtroot commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 2.6)
Moet dit bestand nog bestaan?

2017-05-19 07:26 UTC, sqrtroot commented on modules/template-arduino/CMakeLists.txt
> +    #${hwlib}/library/hwlib.cpp
Moet dit niet wel weer gecompiled worden?

2017-05-19 07:26 UTC, sqrtroot commented on modules/template-arduino/CMakeLists.txt
> +include(${toolchain}/targets/arm32/cm3/atmel/sam3x/sam3x8e/flashscripts/arduino_due.cmake)
Waar staat de define voor arduino due?

2017-05-19 07:26 UTC, sqrtroot commented on modules/template-pc/CMakeLists.txt
> +add_executable(${exe_name} ${sources})
Flags niet included?

2017-05-19 07:26 UTC, sqrtroot commented on modules/template-pi/CMakeLists.txt
> +add_executable(${exe_name} ${sources})
Geen flags included?

2017-05-19 08:20 UTC, cjsmeele commented on modules/template-arduino/CMakeLists.txt
> +    #${hwlib}/library/hwlib.cpp
Nee, zie de wrap-hwlib regel eronder. We includen nergens rechtstreeks hwlib.
Deze regel (en de `set(sources main.cpp)` verder naar boven (waar komt die vandaan?)) kan weg.

2017-05-19 09:43 UTC, sqrtroot commented
Documentation is done @ https://github.com/R2D2-2017/R2D2-2017/wiki/Development-Workflow
Small litle things are done please review
@LuukSteeman @ManDeJan

2017-05-19 10:09 UTC, LuukSteeman commented
Documentation looks good, good work guys.

2017-05-19 10:09 UTC, LuukSteeman approved these changes

2017-05-19 10:12 UTC, merged