Feat navsys graph storage
R2D2-2017/R2D2-2017 pull request #10
Opened 2017-05-24 14:14 UTC by JeremyRuizenaar

Bij deze een pull request voor the graph storagemanager.

Klassen toegevoegd voor deze feature
-StorageManager

Functies aangepast in volgende classes voor deze feature:
-Node class.
-Vertice class.
-Graph class.
 
Functies toegevoegd aan de volgende classes voor deze feature:
-Node class.
-Vertice class.
-Graph class.

De storage manager is geïmplementeerd op de graph class binnen deze feature branch

Leave some feedback

2017-05-29 10:01 UTC, LuukSteeman reviewed
We use a different commenting norm according to chris.
Please replace all comments starting with `///` to ```/*
*
*/```

2017-05-29 10:01 UTC, LuukSteeman commented on modules/NAVSYS/src/graph.cc
> +    nodeFile = fopen(nodeFilePath.c_str(),"w");
Got this warning

Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4996	'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	navsys	C:\Users\luuks\OneDrive\Documenten\HBO-ICT_jaar_2\Periode 4\R2D2\R2D2-2017\modules\NAVSYS\src\graph.cc	64

2017-05-29 10:01 UTC, LuukSteeman commented on modules/NAVSYS/src/graph.cc
> +    verticeFile = fopen(verticeFilePath.c_str(),"w");
Same warning

Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4996	'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	navsys	C:\Users\luuks\OneDrive\Documenten\HBO-ICT_jaar_2\Periode 4\R2D2\R2D2-2017\modules\NAVSYS\src\graph.cc	64

2017-05-29 10:03 UTC, LuukSteeman commented
had to add
`#include <string>`
to prevent bunch of errors in node.hh graphfactory.hh and graph.hh

2017-05-29 17:48 UTC, sqrtroot requested changes
Some small changes and next time please have a look at what you actually commit. If you change white space because it's wrong please make it a commit so you've stated your intentions

2017-05-29 17:48 UTC, sqrtroot commented on modules/NAVSYS/CMakeLists.txt
> +
Too many whitespaces

2017-05-29 17:48 UTC, sqrtroot commented on modules/NAVSYS/src/coordinate.hh
>  #define NAVIGATIONSYSTEM_COORDINATE_HH
A lot of indentation changes in not changed files

2017-05-29 17:48 UTC, sqrtroot commented on modules/NAVSYS/src/graph-factory.cc
> +/*author jeremy
Documentation in .hh

2017-05-29 17:48 UTC, sqrtroot commented on modules/NAVSYS/src/graph-factory.hh
> +using namespace std;
No using namespace std

2017-05-29 17:48 UTC, sqrtroot commented on modules/NAVSYS/src/graph-factory.hh
> +    std::vector<Node>::iterator getNodeByName(std::string name, std::vector<Node> nodes);
Why return the iterator and not the node itself

2017-05-29 17:48 UTC, sqrtroot commented on modules/NAVSYS/src/graph-factory.cc
> +    Graph * graph = new Graph();
Your documentation(the one that is missing) doesn't show the use of new in this function, this probably is going to create memory leaks. Either document this very clear or change the use of new

2017-05-29 17:48 UTC, sqrtroot commented on modules/NAVSYS/src/graph-input.cc
> +void GraphInput::getNodeEntryFromScreen(Graph * graph) {
Why not use references, raw pointers are unsafe

2017-05-29 17:48 UTC, sqrtroot commented on modules/NAVSYS/src/graph.cc
> +void Graph::dumpGraphToDisk(const std::string nodeFilePath,const std::string verticeFilePath) {
Is this a task of the graph or of the factory or of something else? plz discus

2017-05-29 17:48 UTC, sqrtroot commented on modules/NAVSYS/src/graph.hh
> +    std::vector<Node> nodes;
Again a lot of white space changes in unrelated files

2017-05-29 18:12 UTC, sqrtroot commented
To change the unsave fopen warning you could use ifstreams

2017-05-30 00:42 UTC, JeremyRuizenaar commented on modules/NAVSYS/src/graph-input.cc
> +void GraphInput::getNodeEntryFromScreen(Graph * graph) {
fixed

2017-05-30 00:42 UTC, JeremyRuizenaar commented on modules/NAVSYS/src/graph-factory.hh
> +using namespace std;
fixed

2017-05-30 00:42 UTC, JeremyRuizenaar commented on modules/NAVSYS/src/graph-factory.cc
> +/*author jeremy
fixed

2017-05-30 00:45 UTC, JeremyRuizenaar commented on modules/NAVSYS/src/graph.hh
> +    std::vector<Node> nodes;
noticed.

2017-05-30 00:50 UTC, JeremyRuizenaar commented on modules/NAVSYS/src/graph-factory.hh
> +    std::vector<Node>::iterator getNodeByName(std::string name, std::vector<Node> nodes);
I did not know this was possible, fixed

2017-05-30 01:04 UTC, JeremyRuizenaar commented on modules/NAVSYS/src/graph.cc
> +void Graph::dumpGraphToDisk(const std::string nodeFilePath,const std::string verticeFilePath) {
The factory only creates the graph. I have put the responsibility of storing the graph at the graph itself.

 Back when  i worked on it i  did not see any reason to have the factory do anything else besides creating the graph.

2017-05-30 01:18 UTC, JeremyRuizenaar commented on modules/NAVSYS/src/graph.cc
> +    verticeFile = fopen(verticeFilePath.c_str(),"w");
fixed

2017-05-30 01:55 UTC, JeremyRuizenaar commented on modules/NAVSYS/CMakeLists.txt
> +
fixed

2017-05-30 02:34 UTC, JeremyRuizenaar commented on modules/NAVSYS/src/graph-factory.cc
> +    Graph * graph = new Graph();
Removed the use of new, but stumbled across a different problem of the created graph being destroyed at the end of the function. I have circumvented this by doing the following:
GraphFactory factory = GraphFactory();               
Graph g = Graph();                                   
factory.createGraph(nodeFilePath,verticeFilePath, g); 

This however required the graph to be initialized(empty) and then passed to the createGraph() function.
Let me know if this is allright.

2017-05-30 07:04 UTC, sqrtroot approved these changes

2017-05-30 07:04 UTC, merged