Feat navsys sfml
R2D2-2017/R2D2-2017 pull request #15
Opened 2017-05-30 21:57 UTC by leojenns

@philippezwietering @sqrtroot @LuukSteeman @JeremyRuizenaar @Vallkyr1

2017-05-31 09:15 UTC, philippezwietering approved these changes
Ziet er verder prima uit, moet alleen nog verwerkt worden in de run() functie aan de client side

2017-05-31 09:15 UTC, philippezwietering commented
Als je wilt dat mensen kunnen reviewen, moet je rechts in onder het kopje "Reviewers" revieweres selecteren, dan kunnen we daadwerkelijk approven etc.

2017-06-04 19:07 UTC, Bob-Thomas requested changes

2017-06-04 19:07 UTC, Bob-Thomas commented on modules/NAVSYS/client/graphicsgraph.cc
> +	while (window.isOpen()) {
shouldn't the window.isOpen() be in a input update loop?
because now you're handling input in a draw function which could cause confusion

2017-06-04 19:07 UTC, Bob-Thomas commented on modules/NAVSYS/client/graphicsgraph.hh
> +	void reload(Graph * g);
Document params ?

2017-06-04 19:07 UTC, Bob-Thomas commented on modules/NAVSYS/client/graphicsnodes.hh
> +	* the constructor contains twe parameters, The first one is the position of the node in the sfml window.
Document params in the doxygen style

2017-06-04 19:07 UTC, Bob-Thomas commented on modules/NAVSYS/client/graphicsvertices.cc
> +GraphVertice::GraphVertice(sf::Vector2f positiona,sf::Vector2f positionb) :
camelCase

2017-06-05 20:25 UTC, leojenns commented on modules/NAVSYS/client/graphicsgraph.cc
> +	while (window.isOpen()) {
i didn't noticed it i have changed it

2017-06-05 20:56 UTC, leojenns commented on modules/NAVSYS/client/graphicsvertices.cc
> +GraphVertice::GraphVertice(sf::Vector2f positiona,sf::Vector2f positionb) :
i have changed it in the right way

2017-06-05 20:56 UTC, leojenns commented on modules/NAVSYS/client/graphicsnodes.hh
> +	* the constructor contains twe parameters, The first one is the position of the node in the sfml window.
changed it

2017-06-05 20:56 UTC, leojenns commented on modules/NAVSYS/client/graphicsgraph.hh
> +	void reload(Graph * g);
changed it

2017-06-06 07:15 UTC, Bob-Thomas approved these changes

2017-06-06 07:16 UTC, merged