Feat gas
R2D2-2017/R2D2-2017 pull request #16
Opened 2017-05-31 11:16 UTC by DavidDriessen

@DavidDriessen @kasumi-owari @cjsmeele @StpdFox @JeroenKok

2017-05-31 11:51 UTC, sqrtroot requested changes
Looks good except some minor details see comments below

2017-05-31 11:51 UTC, sqrtroot commented on .gitmodules
> -	url = https://github.com/sqrtroot/toolchain.git
Please reset to original tool chain git, since the reason this probably was used is merged upstream

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/alarm.hh
> +    /// \brief Constructor for Alarm
Two doxygen style's used in same file choose 1 please

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/data-logger.cc
> +    for (unsigned int i = 0; i < 512 / sizeof(uint32_t); i++) {
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/data-logger.cc
> +    index = totalMeasurements % (512 / sizeof(float));
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/data-logger.cc
> +    for (unsigned int i = 0; i < 512 / sizeof(float); i++) {
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/data-logger.cc
> +    if (index >= 512 / sizeof(float)) {
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/data-logger.hh
> +    uint32_t header[512 / sizeof(uint32_t)];
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/data-logger.hh
> +    float buffer[512 / sizeof(float)];
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/hwlib-due-spi.hh
> +            SPI0->SPI_CSR[0] = (  (uint32_t)32 << 24
Magic Numbers

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/main.cc
> +    return ((float)sensor.get()) / 4096.0f * 3.3f;
Magic Numbers

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/main.cc
> +        hwlib::wait_us((int_fast32_t) (5000000 - (hwlib::now_us() - time)));
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/sd-spi.cc
> +    uint8_t str[6];
Magic Numbers

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/sd-spi.cc
> +        str[5] = 0xff; // ¯\_(ツ)_/¯
Please implement CRC

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/sd-spi.cc
> +    if ((respToken & 0x1f) == 0x05) {
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/sd-spi.cc
> +    uint8_t result = send(SdCommand{17, (uint32_t)pos});
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/sd-spi.cc
> +    uint8_t result = send(SdCommand{24, (uint32_t)pos});
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/sd-spi.cc
> +    return sendBlock((uint8_t*)buffer, 512);
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/sd-spi.cc
> +    result = send(SdCommand{8, 0x1a5});
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/sd-spi.cc
> +        if ((cmd8Buf[2] & 0x0f) != 1)
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/sd-spi.cc
> +        if (cmd8Buf[3] != 0xa5)
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/sd-spi.cc
> +        result = send(SdCommand{55, 0});
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/sd-spi.cc
> +        result = send(SdCommand{41, 1UL << 30});
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/sd-spi.cc
> +    result = send(SdCommand{9, 0});
Magic Number

2017-05-31 11:51 UTC, sqrtroot commented on modules/GAS/src/sd-spi.cc
> +          (uint32_t)(csdb[7] & 0x3f) << 16
Magic Number

2017-05-31 11:55 UTC, cjsmeele commented on modules/GAS/src/sd-spi.cc
> +          (uint32_t)(csdb[7] & 0x3f) << 16
See the bitfield above for documentation.
It doesn't really make sense to create a constant for this if you ask me.

2017-05-31 11:57 UTC, sqrtroot commented on modules/GAS/src/sd-spi.cc
> +          (uint32_t)(csdb[7] & 0x3f) << 16
Maybe make a comment like `//see bitfields`

2017-05-31 11:58 UTC, cjsmeele commented on modules/GAS/src/data-logger.cc
> +    for (unsigned int i = 0; i < 512 / sizeof(uint32_t); i++) {
NB: Block size can be queried from the store using the `getBlockSize()` method.

2017-05-31 12:04 UTC, cjsmeele commented on modules/GAS/src/sd-spi.cc
> +        str[5] = 0xff; // ¯\_(ツ)_/¯
Sounds like a good plan for a future sprint, to improve reliability & data integrity.

2017-05-31 12:12 UTC, DavidDriessen commented on modules/GAS/src/main.cc
> +        hwlib::wait_us((int_fast32_t) (5000000 - (hwlib::now_us() - time)));
5 seconds between measurements. See wiki https://github.com/R2D2-2017/R2D2-2017/wiki/Gas-safety-system

2017-05-31 16:56 UTC, sqrtroot commented on modules/GAS/src/main.cc
> +        hwlib::wait_us((int_fast32_t) (5000000 - (hwlib::now_us() - time)));
doesn't make it less of a magic number, define it in a constant so people can change it if it's needed

2017-06-01 10:54 UTC, DavidDriessen commented
![](https://github.trello.services/images/mini-trello-icon.png) [David Driessen](https://trello.com/c/JNTYVBv1/28-david-driessen)

2017-06-06 07:46 UTC, cjsmeele commented on modules/GAS/src/sd-spi.cc
> +          (uint32_t)(csdb[7] & 0x3f) << 16
I think the comment a few lines up covers this:
```c++
    SdCsd csd;

    // For some reason bitfields are broken. We accecss it as a byte
    // array instead. Meh.
    uint8_t *csdb = (uint8_t*)&csd;
```

2017-06-21 09:50 UTC, cjsmeele commented
Superseded by #32.

2017-06-21 09:50 UTC, closed without merging