Feat rfid
R2D2-2017/R2D2-2017 pull request #19
Opened 2017-06-01 14:31 UTC by arcogelderblom

2017-06-01 16:05 UTC, cjsmeele requested changes
I find a number of issues with the quality of this code.

What stood out the most:

- General programming/C++-specific deficiencies: Please improve the structure and general code quality based on the comments.
- Style issues: The code deviates considerably from the coding guidelines. Please review the wiki and the linked LLVM guidelines and update your code accordingly.
- Security issues: Do not ever put sensitive information like database connection details in version control.

Please note that I may have stopped commenting on some style issues along the way of this review. Take note of the first style issues and apply them to the rest of the module.

What I would like to note as well:
- You've put a very good amount of attention to documentation! I saw most things covered by docblocks and inline comments. Keep it up.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/encryption.cc
> +encryptKey = 1;
Style issues: Indentation and space before brace.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/encryption.cc
> +Encryption::Encryption(int encryptionKey){
This would be better as a single constructor with a default parameter value.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/encryption.cc
> +std::string Encryption::Decrypt(std::string input, int keyCode){
No need to take the input as a value. Pass it as a constref instead.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/encryption.cc
> +        restr[i] = restr[i]-keyCode ;
Move the space before the `;` to the point before the brace on the previous line.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/encryption.cc
> +std::string Encryption::Encrypt(std::string input, int keyCode){
Pass as constref, not by value.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/encryption.cc
> +	encryptKey = encryptionKey;
Please use an initializer list instead. Since you don't have a constructor body it would be cleaner to have the constructor inline in the header.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/encryption.hh
> +#define ENCRYPTION_HH
Please use `#pragma once` instead of ifdef include guards. It's cleaner and less error-prone.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/encryption.hh
> +	 * Contructor for if your using fixed key
Docblock is not a docblock due to a missing asterisk.
Also, there's a tab in the indentation here instead of spaces.
Prefix your brief line with `\brief`.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/encryption.hh
> +     * \param[in,out] keyCode that will be used the encrypt the string with a specific key
Input and keycode are not `[in,out]` parameters.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/encryption.hh
> +    int encryptKey;
Minor detail, but please place private members at the top of the class, before public members.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/led-controller.hh
> +    void blinkLed(int pin, int time);
Why have a class for this function only?
And when you make it a class, why not make the pin a member so you don't have to pass it to the method every time?

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/led-controller.hh
> + /**
Indentation missing. Spaces missing before opening braces on previous lines.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/main.cc
> + * \brief     Combination of the work of sprint 1
This is a description of *when* you made the work, not *what* the work is actually about.
Try to condense the functionality in this file into a concise one-liner.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/main.cc
> +    if(!connection.connectTo("192.168.2.50", "R2D2", "BB8")){
Magic values!
This seems better suited for a configuration file. *Especially* the password, you don't ever want db connection info in version control.
Additionally, minor style issue with missing spaces around the condition. See the coding guidelines.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/main.cc
> +    std::cout<<"Made connection to the database\n";
Missing spaces around operator.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/main.cc
> +    Encryption encryption(65341);
This value and the pins above should be either constants or configuration values.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/main.cc
> +    while(1){
Prefer `while (true)` in C++.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/main.cc
> +return 0;
Indentation missing. Also spaces missing around the conditions in the `if` and `while`s further up.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/matrix-keypad.cc
> +    const int * column,
Glue the asterisk to the identifier: `const int *row`

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/matrix-keypad.cc
> +    return i;
Some style issues above, same as commented elsewhere (spaces, asterisks).

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/matrix-keypad.hh
> +    char keypad[4][4] = {
Should this not be (static) const?
Additionally, the column size appears to be variable later on, but it's always 4 here. Why?

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/matrix-keypad.hh
> +    const int colSize;
Why is colSize not initialized?

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.cc
> +}
Since you're manipulating bits, it would be more readable to specify `uint8_t` as the type instead of `unsigned char`. This also applies elsewhere in this file.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.cc
> +    writeRegister(0x01, 0x0F); //Send softReset command.
You've defined the soft reset value in an enum, use it!

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.cc
> +                            unsigned int receiveDataLen){
Either align the parameter list by moving these to the right, flagpost style, or move the first and last parameter into separate lines and decrease the indentation.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.cc
> +    writeRegister(commandReg, command); //execute command
Please realign the comments or don't align them at all.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.cc
> +		delay(1);
Tabs out of nowhere!

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.cc
> +    while(1){
`while (true)` is preferable in C++.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.cc
> +        return 1;
Functions returning `bool` must return `true` or `false`, not implicitly converted integers.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.cc
> +    data[0] = mifareReqIdle; // first element is the command to send to the tag. Here we request every tag that is in idle
Use a single `char` and pass its address to the function below.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.cc
> +    unsigned char status = communicateWithTag(transceive, data, 1, nullptr, 0); // nullptr beacause we do not need ro read data from the tag.
You compare status with an enum value below. Shouldn't you get it as an enum value from this function as well?

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.hh
> +#include <stdint.h>
Use the style `<cstdint>` for C standard library headers in C++.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.hh
> +    enum mifareCommands{
Use an enum class and remove the `mifare` prefix from the identifiers below.
Additionally since these values appear to be of a fixed width (as used in the protocol / registers), you can use `enum class MifareCommands : uint8_t` to specify the underlying integer type.
At the point where you actually write the values to something expecting a `uint8_t`, `static_cast` them to that type.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.hh
> +    enum mfrc522Commands{
Same as above, use an enum class so that the names are scoped to the enum instead of the containing class.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.hh
> +	PICC_TYPE_NOT_COMPLETE	= 255	/** SAK indicates UID is not complete.*/
You use hexadecimal values above and decimal here. Any particular reason why?

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.hh
> +    enum PICC_Type {
enum classs
remove `PICC_TYPE` prefix from names within.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.hh
> +    enum mfrc522Registers{
Enum class, and remove the `Reg` suffix from names within.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.hh
> +    enum statusCodes{
Enum classes. Also specify `uint8_t` as the size, like earlier in the review.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.hh
> +    void writeRegister(unsigned char address, unsigned char * value, unsigned int len);
I don't see `value` being changed anywhere down the call chain. Mark it `const` if this is correct. Otherwise, mark it as `[in,out]`.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.hh
> +    unsigned char readRegister(unsigned char address);
Prefer `uint8_t` when not dealing with actual characters/strings.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.hh
> +     * \return The function returns a status code. statusOk for succes, statusTimeout if no tag was found or a statusError if something else went wrong
When you have a limited set of possible return values, as is the case with enums such as these, it's clearer if you document them like this:
```
\retval enumValue1 When things go right
\retval enumValue2 When things go horribly wrong
....
```

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.hh
> +                       unsigned int receiveDataLen);
Align params together or put them on separate lines with less indentation.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mfrc522.hh
> +                       unsigned char * sendData,
`sendData` is marked as an input parameter. Make it `const` if it is not changed within the function. Otherwise mark it `[in,out]`.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mysql.hh
> +    sql::Driver * driver;
Use smart pointers (probably unique pointer in this case).
This makes memory management easier and a lot less error-prone.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mysql.cc
> +    delete connection;
As noted in the header, use smart pointers so you don't have to worry about deallocation.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mysql.cc
> +bool MySql::connectTo(std::string url, std::string username, std::string password){
Pass these as const refs, not by value. Same for the functions below.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mysql.cc
> +    return true;
What's the point of discarding error information?
If the caller doesn't care if something succeeded or not, you might as well create an `ignoreErrors(T)` function.
Otherwise, allow the caller to handle errors by *not* reducing it to a boolean and rethrowing the exception instead, so the caller has more information.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mysql.cc
> +    std::string columnInformation = "";
Unnecessary initialization.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mysql.hh
> +#include "mysql_connection.h"
If this is a system/library header, use angle brackets instead of quotes.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mysql.hh
> +    /// Checks for errors when executing function of template type T.
Suddenly a different style of docblock. Please use the `/** */` form like you used elsewhere in this module.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/src/mysql.hh
> +    ///     connectTo("tcp://192.168.2.50:3306", "R2D2", "BB8");
Please don't use actual db connection info including passwords in examples.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/CMakeLists.txt
> +    src/matrix-keypad.hh
Remove the headers from the list of sources - you only need the cc files here.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/Set up database/mysql-install.sh
> +sudo apt-get update && sudo apt-get upgrade
I like that you added an install script, but I suggest you remove the `update`/`upgrade`, as it is irrelevant to the installation of this module.

2017-06-01 16:05 UTC, cjsmeele commented on modules/RFID/Set up database/mysql-install.sh
> +
Add a shebang line like this: `#!/bin/sh` to aid Linux in finding the right interpreter for this file.

2017-06-01 16:33 UTC, sqrtroot requested changes
I would like to add some notes to @cjsmeele review see them attached below.
Also although this was probably just a stub version of the encryption algorithm needed to complete the vertical slice. This is really really insecure. It isn't shown in the documentation. Someone could accidentally use this thinking it will provide a secure encryption algorithm. Please show this in your documentation.

2017-06-01 16:33 UTC, sqrtroot commented on modules/RFID/CMakeLists.txt
> +target_link_libraries(${exe_name} mysqlcppconn)
please use a find library module

2017-06-01 16:33 UTC, sqrtroot commented on modules/RFID/CMakeLists.txt
> +target_link_libraries(${exe_name} ${WIRINGPI_LIBRARIES})
please don't link twice

2017-06-01 16:33 UTC, sqrtroot commented on modules/RFID/Set up database/R2D2.sql
> +  `NAAM` text NOT NULL,
English

2017-06-01 16:33 UTC, sqrtroot commented on modules/RFID/Set up database/R2D2.sql
> +  `FUNCTIE` text NOT NULL,
English

2017-06-01 19:11 UTC, cjsmeele commented on modules/RFID/CMakeLists.txt
> +target_link_libraries(${exe_name} mysqlcppconn)
^ To clarify Robert's comment, CMake has support for detecting libraries such as MySQL regardless of the platform you're working on. Using this feature improves error reporting, handling of version differences and required flags, and finding of library paths.

You can look [here](https://cmake.org/Wiki/CMakeUserFindMySQL) for an example on how to detect MySQL. It would be nice if this could be added as a CMake module, although it would probably be best if we (leads) gave some pointers / support on how to add a module and how to set the appropriate flags after this. I hope you can help them out with this one @sqrtroot ? Otherwise I will be available to look at it with you next week.

2017-06-01 19:40 UTC, Bob-Thomas commented on modules/RFID/Set up database/mysql-install.sh
> +sudo apt-get update && sudo apt-get upgrade
And upgrading is not always good in this case

2017-06-01 19:55 UTC, sqrtroot commented on modules/RFID/CMakeLists.txt
> +target_link_libraries(${exe_name} mysqlcppconn)
I'll help them if they can't figure it out :) pm me with any issues

2017-06-02 18:20 UTC, timijntema commented on modules/RFID/src/matrix-keypad.hh
> +    const int colSize;
collSize dus get initialized. The initialization hapens in the constructor with the standard value of 3 but the option to give the constructor a 4 due to some keypads only having 3 columns.

2017-06-02 18:23 UTC, timijntema commented on modules/RFID/src/matrix-keypad.hh
> +    char keypad[4][4] = {
The column size is variable due to some keypads having 3 columns but in the array with character that dus not matter. The code will just not do anything with the 4th column if a 3x3 keypad is attached. It still has to be there for 4 column keypads

2017-06-02 22:53 UTC, cjsmeele commented on modules/RFID/src/matrix-keypad.hh
> +    char keypad[4][4] = {
Okay. There appears to be a possibility for an out-of-bounds read in `getKey()` when `colSize` is too large (or negative). Please add validation to this parameter, either by making it constexpr and doing `static_assert` (if it's always known at compile-time) or otherwise with some code in the constructor.

2017-06-05 18:07 UTC, cjsmeele commented on modules/RFID/src/file-factory.cc
> +    incorrectLineCheck(encryptionKey == (int)"\n");
You're casting a `const char*` to an `int` here, probably not what you intended.

2017-06-05 18:10 UTC, cjsmeele commented on modules/RFID/src/file-factory.hh
> +    void incorrectLineCheck(const bool & toCheck, const std::string & fileName, const int & line);
Fundamental types (e.g. `int`) should be passed by value, not as constref.

2017-06-05 18:15 UTC, cjsmeele commented on modules/RFID/src/matrix-keypad.cc
> +    /**
The `/** */` comment form is a doxygen docblock. Use it only for file headers, types, declarations and for functions and variables that don't have a separate declaration.
Use `//` or `/* */` style comments otherwise.

2017-06-05 18:19 UTC, cjsmeele commented on modules/RFID/src/mysql.hh
> +    /*
Missing a second asterisk to make it a docblock.

2017-06-05 18:21 UTC, cjsmeele commented on modules/RFID/src/file-factory.cc
> +                + "\nWhile reading from: " + nameCurrentFile + " line: " + std::to_string(lineCurrentFile));
Please do not throw raw strings.
Use `std::runtime_error` from `<stdexcept>` instead.

2017-06-05 18:23 UTC, cjsmeele commented on modules/RFID/src/file-factory.hh
> +class FileFactory {
The class name is a misnomer: It's not a factory for files. Consider for example `ConfigFileParser` instead.

2017-06-05 18:26 UTC, cjsmeele commented
You're moving in the right direction, I've added a few comments on the new code.

2017-06-06 08:18 UTC, arcogelderblom commented
Changed a couple of files based on the feedback we've got.

2017-06-22 09:35 UTC, merged