created check runner in bmptk
R2D2-2017/R2D2-2017 pull request #2
Opened 2017-05-21 19:42 UTC by sqrtroot

created check runner in bmptk so people can run our check suite
clang-tidy and cppcheck are supported at the moment

2017-05-21 20:09 UTC, Bob-Thomas commented
+1
neat functionality so we can actually run checks without waiting on jenkins

2017-05-21 20:36 UTC, ManDeJan commented
+1, good functionality. Code also looks clean, also worked as expected when I tested it. I approve for a merge.

2017-05-21 20:37 UTC, ManDeJan submitted a review, later dismissed
Tested and approved for merge

2017-05-21 21:23 UTC, cjsmeele requested changes
Looks good overall and adds a very useful feature!
There's only a small issue with selecting the right clang-tidy binary, see other comment.

2017-05-21 21:23 UTC, cjsmeele commented on bmptk++.py
> +            tidy_command = 'clang-tidy-3.8 -header-filter=.* -p={0} -checks=* {1}'.format(
Why depend on this specific clang-tidy version?
At least on my machine (Debian 8) `clang-tidy` is in my path, but this script won't run it as it is a different version.

2017-05-22 07:35 UTC, sqrtroot commented on bmptk++.py
> +            tidy_command = 'clang-tidy-3.8 -header-filter=.* -p={0} -checks=* {1}'.format(
This is how the official python script did it. I agree that it's not the correct way change is incoming :)

2017-05-22 10:13 UTC, ManDeJan commented on bmptk++.py
> +            tidy_command = 'clang-tidy-3.8 -header-filter=.* -p={0} -checks=* {1}'.format(
clang-tidy-3.8 is a separate package then clang-tidy on my linux mint system so I thats why I did not encouter problems when testing

2017-05-22 10:14 UTC, ManDeJan submitted a review, later dismissed
Requested changes have been made, ok to merge.

2017-05-22 10:35 UTC, cjsmeele commented
I have an arduino module that has the following code in `main.cc`:
```c++
// Unused arguments
int f(int a, int b) { return 5; }                                                                                  

int main() {
    WDT->WDT_MR = WDT_MR_WDDIS;

    int x; // uninitialized variable passed to f
    int y;
    y = 5;
         y++; // (4 spaces + 1 tab char)
    f(x, y);

    // (...)
}
```

Running `bmptk++.py` with command `check -m GAS` gives the following output:

```
Command: check -m GAS
Checking module GAS
[Cppcheck]main.cc:14  Uninitialized variable
```

Can you confirm that it should only catch this one warning?
Should the other issues not be caught?

For reference, this is on Arch with clang-tidy 4.0 and cppcheck 1.79.

2017-05-22 10:39 UTC, sqrtroot commented
@cjsmeele 
The current test runners (clang-tidy and cppcheck) do not check all style issues. Clang-format has to be implemented to generate these errors. The problem is that clang-format does not output the errors it has found in the styling only a formated version of the input file.

@R2D2-2017/leads Maybe we have to take a look at the implementation of clang-format to see if we can generate these kinds of errors ourself based on the tooling in llvm?

2017-05-22 10:52 UTC, cjsmeele commented
@sqrtroot Agreed. I'll approve this PR with the understanding that we're going to extend this feature in the near future.

2017-05-22 10:52 UTC, cjsmeele submitted a review, later dismissed

2017-05-22 11:26 UTC, sqrtroot commented
After some more digging I found the reason the unused arguments are not found by clang-tidy. Apperently it doesn't go well with the generated compile_commands.json file and probably arm-none-eabi-g++ 
If i run ` clang-tidy -header-filter=.* -checks=* R2D2-2017/modules/TEST/src/main.cc` (main.cc contains the code mentioned above) it generates the following output:
```
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "R2D2-2017/modules/TEST/src/main.cc"
No compilation database found in R2D2-2017/modules/TEST/src or any parent directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
2 warnings and 2 errors generated.
Error while processing R2D2-2017/modules/TEST/src/main.cc.
R2D2-2017/modules/TEST/src/main.cc:2:11: warning: parameter 'a' is unused [misc-unused-parameters]
int f(int a, int b) { return 5; }                                                                                  
          ^
           /*a*/
R2D2-2017/modules/TEST/src/main.cc:2:18: warning: parameter 'b' is unused [misc-unused-parameters]
int f(int a, int b) { return 5; }                                                                                  
                 ^
                  /*b*/
R2D2-2017/modules/TEST/src/main.cc:5:5: error: use of undeclared identifier 'WDT' [clang-diagnostic-error]
    WDT->WDT_MR = WDT_MR_WDDIS;
    ^
R2D2-2017/modules/TEST/src/main.cc:5:19: error: use of undeclared identifier 'WDT_MR_WDDIS' [clang-diagnostic-error]
    WDT->WDT_MR = WDT_MR_WDDIS;

```
so without the compilation database it does find the unused parameters but it errors on undeclared identifiers

2017-06-06 19:27 UTC, sqrtroot commented
It took some time and is a bit hacky but luckily it finally works for arduinos.
Please review @cjsmeele @ManDeJan

2017-06-07 16:41 UTC, ManDeJan approved these changes
If it's hacky and you know it clap your hands *clap* *clap*
If you aprove for merging and you know it clap your hands  *clap* *clap*'

I don't see how else we could get this working in time and it works, and nobody has to see or touch it, so I approve.
Nice work :) 👍

2017-06-16 13:52 UTC, merged